[package]
name = "aperisyvra"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Command-line tool for the AperiSyVra P1 profile"

[dependencies]
anyhow.workspace = true
aperisyvra-core = { path = "../aperisyvra-core" }
clap.workspace = true
rand.workspace = true
